contents:
  packages:
    - glibc-locale-en
    - busybox
    - maven
    - openjdk-21
    - openjdk-21-default-jvm

accounts:
  groups:
    - groupname: maven
      gid: 65532
  users:
    - username: maven
      uid: 65532
  run-as: 65532

work-dir: /home/build

entrypoint:
  command: /usr/bin/mvn

environment:
  LANG: en_US.UTF-8
  JAVA_HOME: /usr/lib/jvm/java-21-openjdk

paths:
  - path: /home/build
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o755
