apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: has-sbom-attestation
spec:
  images:
    - glob: ghcr.io/chainguard-images/testing/release-2.0/*
  authorities:
    - name: keyless-authority
      keyless:
        url: https://fulcio.sigstore.dev
        identities:
          - issuer: https://token.actions.githubusercontent.com
            subject: https://github.com/chainguard-images/images/.github/workflows/release-2.0.yaml@refs/heads/release-2.0
      ctlog:
        url: https://rekor.sigstore.dev
      attestations:
        - name: must-have-sbom-attestation
          predicateType: "https://spdx.dev/Document"
          policy:
            type: cue
            data: |
              predicateType: "https://spdx.dev/Document"
